Add user to database
CS3219-AY2324S1/ay2324s1-course-assessment-g51 pull request #43
Opened 2023-10-14 13:30 UTC by zenithyap

When user creates a new account, or uses SSO for the first time, brings the user to the user page to fill in the user details (all fields must be filled in). The user will not be able to access other pages until the user details are entered and saved. Saving the details transfers the data to the user database (postgres). The user page then gets the user details from the user database and displays it.

2023-10-15 16:25 UTC, Kang-Quan requested changes
Some bugs i have encountered.
1. have not created a profile -> redirected to profile creation page -> tries to go to other pages by changing the url eg /home it does not redirect me back to profile creation.
2. If i log in using github and twitter, Email is not shown.

2023-10-15 16:25 UTC, Kang-Quan commented on front-end/peer-prep/src/components/Auth/SignInPage/AuthButton/SignInButton.tsx
> +    provider: GoogleAuthProvider | FacebookAuthProvider | GithubAuthProvider | TwitterAuthProvider;
Good use of interface to combine all 4 provider into 1 file instead of 4 files with mostly duplicated code.

2023-10-15 16:25 UTC, Kang-Quan commented on front-end/peer-prep/src/components/Auth/SignInPage/index.tsx
> +                        if (password !== secondPassword) {
Good catch

2023-10-17 04:37 UTC, zenithyap commented
> Some bugs i have encountered.
> 
> 1. have not created a profile -> redirected to profile creation page -> tries to go to other pages by changing the url eg /home it does not redirect me back to profile creation.
> 2. If i log in using github and twitter, Email is not shown.

2023-10-17 07:14 UTC, Kang-Quan approved these changes
able to see email in profile for all services. Unable to route to other page via url now which is intended. LGTM

2023-10-17 07:15 UTC, merged